### ISSUE TITLE
Kubernetes yaml option

### ISSUE THREAD

**Issue by cpt-redbeard** [aquasecurity/harbor-scanner-aqua#45]
#44 Would it be possible to get a bare kubernetes yaml for helm-less deployments?

**Comment by danielpacak** [comment]
You can always template out Kubernetes yaml descriptors from the existing Helm chart and pipe it to `kubectl apply -f -` even if you don't want to install it with Helm:

```
$ helm template harbor-scanner-aqua ./helm/harbor-scanner-aqua \
    --namespace harbor \
    --set service.port=8443 \
    --set scanner.api.tlsEnabled=true \
    --set scanner.api.tlsCertificate="`cat tls.crt`" \
    --set scanner.api.tlsKey="`cat tls.key`" \
    --set aqua.version=$AQUA_VERSION \
    --set aqua.registry.server=registry.aquasec.com \
    --set aqua.registry.username=$AQUA_REGISTRY_USERNAME \
    --set aqua.registry.password=$AQUA_REGISTRY_PASSWORD \
    --set scanner.aqua.username=$AQUA_CONSOLE_USERNAME \
    --set scanner.aqua.password=$AQUA_CONSOLE_PASSWORD \
    --set scanner.aqua.host=http://csp-console-svc.aqua:8080 | kubectl apply -f -
```

In this approach you still need the `helm` command to be installed on your system, but overall it simplifies the maintenance of the deployment descriptors as a Helm chart. What's more there are some values that you have to provide as an input during the install, that we cannot hardcode to sensible defaults.

I hope that helps @cpt-redbeard

**Comment by danielpacak** [comment]
@cpt-redbeard can we close this one?

**Comment by cpt-redbeard** [comment]
Yes, thank you.
