### ISSUE TITLE
Clarify Aqua assurance policies and results displayed in the Harbor interface

### ISSUE THREAD

**Issue by danielpacak** [aquasecurity/harbor-scanner-aqua#54]

**Comment by oliverbutanowitz** [comment]
Hello @danielpacak 
Not sure if it fits into this issue, but it would be great if **malware-findings** from the scannercli would be displayed also in the Harbor-Interface.
I did some testing, i can see that the scannercli debug info is showing 
_summary":{"total":1,"critical":0,"high":0,"medium":1,"low":0,"negligible":0,"sensitive":0,"malware":6}_
but within Harbor, i do not see any info about the malware.

**Comment by danielpacak** [comment]
👋 @oliverbutanowitz In short, displaying malware or sensitive data in Harbor Portal would require changes to the [Pluggable Scanners API v1.1](https://github.com/goharbor/pluggable-scanner-spec), which is owned by Harbor community and contributed to by other security vendors.

This particular adapter just implements the API v1.0 and communicates with the Aqua server to fulfil the contract. However, currently the API and Harbor Portal are only capable of handling and displaying vulnerabilities (see `VulnerabilityItem` object in the API spec). To see the whole report generated by the Aqua scanner you have to navigate from Harbor Portal to Aqua Management Console.

If you want to add more details such as malware or sensitive data to the information that Harbor retrieves from a pluggable scanner, like this one, this would be a RFE to the Pluggable Scanners API. Normally it involves writing a proposal and discussing the whole idea with Harbor maintainers before we start any coding tasks.

**Comment by oliverbutanowitz** [comment]
@danielpacak thanks for your detailed explanation!
